### PR TITLE
The First Big Merge

### PR DESCRIPTION
**Pull request by JoeBiller**
The the purpose of this merge is to:
- Finally mark all the issues as closed.
- Teach everyone how the review system works.
- Walk through each file and explain its role.

### CODE REVIEW

**Review by mitchjtoth — APPROVED** [review]
Everything looks good

**Review by MooseOppai — APPROVED** [review]
have reviewed

**Review by Mak0918 — COMMENTED** [review]
Great work talking the code out. Appreciated

**Review by Mak0918 — APPROVED** [review]
great review.

**Pull request merged**
