### PR TITLE
Initial sprint 3 changes

### PR DESCRIPTION
**Pull request by JoeBiller**
Initial changes for Sprint 3.
These changes include: like, comments, friends, sharing, and bug fixes.

### CODE REVIEW

**Review by MooseOppai — COMMENTED** [review]
looks good!

**Review by mitchjtoth — APPROVED** [review]
Nice work everyone

**Comment by MooseOppai** [comment]
looks good!

**Comment by MooseOppai** [comment]
looks good!

**Review by MooseOppai — APPROVED** [review]

**Review by Mak0918 — APPROVED** [review]

**Pull request merged**
